<?php
// ---------------------------------------------------------------------------
//
// Http header definitions
// This file read by httpheader.class.php
//
// Keys:
//   'client' => {bool}
//   'request' => {bool}
//   'response' => {bool}
//   'fetch-Meta' => {bool}
//   'tags' => {array}
//    'unwantedregex' => {string} regex for unwanted values (eg. version numbers)
//
// ---------------------------------------------------------------------------
return [
    // en: https://en.wikipedia.org/wiki/List_of_HTTP_header_fields
    // de: https://de.wikipedia.org/wiki/Liste_der_HTTP-Headerfelder
    // ... plus https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
    'http' => [
        '_status' => ['response' => true],

        'Accept' => ['client' => true],
        'Accept-Additions' => [],
        'Accept-CH' => ['client' => true],
        'Accept-Charset' => ['client' => true],
        'Accept-CH-Lifetime' => ['client' => true],
        'Accept-Encoding' => ['client' => true],
        'Accept-Features' => [],
        'Accept-Language' => ['client' => true],
        'Accept-Patch' => ['response' => true],
        'Accept-Ranges' => ['response' => true],
        'Access-Control-Allow-Credentials' => ['response' => true, 'tags' => ['cors']],
        'Access-Control-Allow-Headers' => ['response' => true, 'tags' => ['cors']],
        'Access-Control-Allow-Methods' => ['response' => true, 'tags' => ['cors']],
        'Access-Control-Allow-Origin' => ['response' => true, 'tags' => ['security', 'cors']],
        'Access-Control-Expose-Headers' => ['response' => true, 'tags' => ['cors']],
        'Access-Control-Max-Age' => ['response' => true, 'tags' => ['cors']],
        'Access-Control-Request-Headers' => ['response' => true, 'tags' => ['cors']],
        'Access-Control-Request-Method' => ['response' => true, 'tags' => ['cors']],
        'Activate-Storage-Access' => ['response' => true, 'tags' => ['experimental']],
        'Age' => ['response' => true, 'tags' => ['cache']],
        'A-IM' => [],
        'Allow' => ['response' => true],
        'Alternates' => [],
        'Alt-Svc' => ['response' => true],
        'Alt-Used' => ['response' => true],
        'Attribution-Reporting-Eligible' => ['response' => true, 'tags' => ['experimental']],
        'Attribution-Reporting-Register-Source' => ['response' => true, 'tags' => ['experimental']],
        'Attribution-Reporting-Register-Trigger' => ['response' => true, 'tags' => ['experimental']],
        'Authentication-Info' => [],
        'Authorization' => ['request' => true, 'tags' => ['auth']],
        
        'Cache-Control' => ['response' => true, 'tags' => ['cache']],
        'C-Ext' => [],
        'Clear-Site-Data' => ['response' => true, 'tags' => ['cache']],
        'C-Man' => [],
        'Connection' => ['response' => true],
        'Content-Base' => [],
        'Content-Digest' => ['request' => true, 'response' => true, 'tags' => ['experimental']],
        'Content-Disposition' => ['request' => true, 'response' => true],
        'Content-DPR' => ['tags' => ['deprecated', 'mon-standard']],
        'Content-Encoding' => ['response' => true, 'tags' => ['compression']],
        'Content-ID' => [],
        'Content-Language' => ['response' => true],
        'Content-Length' => ['response' => true],
        'Content-Location' => ['response' => true],
        'Content-MD5' => [],
        'Content-Range' => ['response' => true],
        'Content-Script-Type' => [],
        'Content-Security-Policy' => ['response' => true, 'tags' => ['security'], 'badvalueregex' => 'unsafe\-'],
        'Content-Security-Policy-Report-Only' => ['response' => true, 'tags' => ['security']],
        'Content-Style-Type' => [],
        'Content-Type' => ['response' => true, 'tags' => ['security']],
        'Content-Version' => [],
        'Cookie' => ['request'=>true],
        'Cookie2' => ['obsolete' => true],
        'C-Opt' => [],
        'C-PEP-Info' => [],
        'Critical-CH' => ['response' => true, 'tags' => ['experimental']],
        'Cross-Origin-Embedder-Policy' => ['response' => true, 'tags' => ['security']],
        'Cross-Origin-Opener-Policy' => ['response' => true, 'tags' => ['security']],
        'Cross-Origin-Resource-Policy' => ['response' => true, 'tags' => ['security']],
        
        'Date' => ['request' => true, 'response' => true, ],
        'DAV' => [],
        'Default-Style' => [],
        'Delta-Base' => [],
        'Depth' => [],
        'Derived-From' => [],
        'Destination' => [],
        'Device-Memory' => ['request' => true,],
        'Dictionary-ID' => ['response' => true, 'tags' => ['experimental']],
        'Differential-ID' => [],
        'Digest' => ['response' => true],
        'DNT' => ['request' => true, 'tags' => ['deprecated', 'non-standard']],
        'Downlink' => ['request' => true, 'tags' => ['experimental']],
        'DPR' => ['tags' => ['deprecated', 'non-standard']],
        
        'Early-Data' => ['request' => true, 'tags' => ['experimental']],
        'ECT' => ['request' => true, 'tags' => ['experimental']],
        'ETag' => ['response' => true, 'tags' => ['cache']],
        'Expect' => ['response' => true],
        'Expect-CT' => ['response' => true, 'tags' => ['deprecated']],
        'Expires' => ['response' => true, 'tags' => ['cache']],
        'Ext' => [],
        
        'Feature-Policy' => [
            'response' => true,
            'tags' => ['feature', 'security', 'deprecated'],
            "directives" => [
                "accelerometer",
                "ambient-light-sensor",
                "autoplay",
                "battery",
                "camera",
                "display-capture",
                "document-domain",
                "encrypted-media",
                "fullscreen",
                "geolocation",
                "gyroscope",
                "layout-animations",
                "legacy-image-formats",
                "magnetometer",
                "microphone",
                "midi",
                "oversized-images",
                "payment",
                "picture-in-picture",
                "publickey-credentials-get",
                "sync-xhr",
                "unoptimized-images",
                "unsized-media",
                "usb",
                "vibrate",
                "vr",
                "wake-lock",
                "xr",
                "xr-spatial-tracking"
            ]
        ],
        'Forwarded' => ['request' => true],
        'From' => ['request' => true],

        'GetProfile' => [],

        'Host' => ['request' => true],

        'Idempotency-Key' => ['request' => true],
        'If' => [],
        'If-Match' => ['request' => true],
        'If-Modified-Since' => ['request' => true],
        'If-None-Match' => ['request' => true],
        'If-Range' => ['request' => true],
        'If-Unmodified-Since' => ['request' => true],
        'IM' => [],
        'Index' => [],
        'Integrity-Policy' => ['response' => true],
        'Integrity-Policy-Report-Only' => ['response' => true],

        'Keep-Alive' => ['response' => true],

        'Label' => [],
        'Large-Allocation' => [],
        'Last-Modified' => ['response' => true],
        'Link' => ['response' => true],
        'Location' => ['response' => true],
        'Lock-Token' => [],

        'Man' => [],
        'Max-Forwards' => ['request' => true],
        'Meter' => [],
        'MIME-Version' => [],

        'Negotiate' => [],
        'NEL' => ['response' => true, 'tags' => ['experimental']],
        'No-Vary-Search' => ['response' => true, 'tags' => ['cache', 'experimental']],

        'Observe-Browsing-Topics' => ['response' => true, 'tags' => ['experimental', 'non-standard']],
        'Opt' => [],
        'Ordering-Type' => [],
        'Origin' => ['request' => true, 'tags' => ['cors']],
        'Origin-Agent-Cluster' => ['response'=>true, 'tags' => ['experimental']],
        'Overwrite' => [],

        'P3P' => [],
        'PEP' => [],
        'Pep-Info' => [],
        'Permissions-Policy' => ['response'=>true, 'tags' => ['experimental'],
            "directives" => [
                "accelerometer",
                "ambient-light-sensor",
                "aria-notify",
                "attribution-reporting",
                "autoplay",
                "bluetooth",
                "browsing-topics",
                "camera",
                "captured-surface-control",
                "compute-pressure",
                "cross-origin-isolated",
                "deferred-fetch",
                "deferred-fetch-minimal",
                "display-capture",
                "encrypted-media",
                "fullscreen",
                "gamepad",
                "geolocation",
                "gyroscope",
                "hid",
                "identity-credentials-get",
                "idle-detection",
                "language-detector",
                "local-fonts",
                "magnetometer",
                "microphone",
                "midi",
                "on-device-speech-recognition",
                "otp-credentials",
                "payment",
                "picture-in-picture",
                "publickey-credentials-get",
                "screen-wake-lock",
                "serial",
                "speaker-selection",
                "storage-access",
                "translator",
                "summarizer",
                "usb",
                "web-share",
                "window-management",
                "xr-spatial-tracking",
            ],
        ],
        'PICS-Label' => [],
        'Position' => [],
        'Pragma' => ['response' => true, 'tags' => ['cache', 'deprecated']],
        'Prefer' => ['request'=>true,
            "directives" => [
                "respond-async",
                "return=minimal",
                "return=representation",
                "wait=<seconds>",
                "handling=lenient",
                "handling=strict",

            ],
        ],
        "Preference-Applied"=>['response'=>true],
        'Priority' => ['request'=>true, 'response'=>true],
        'ProfileObject' => [],
        'Protocol' => [],
        'Protocol-Info' => [],
        'Protocol-Query' => [],
        'Protocol-Request' => [],
        'Proxy-Authenticate' => ['response' => true, 'tags' => ['auth']],
        'Proxy-Authentication-Info' => [],
        'Proxy-Authorization' => ['response' => true, 'tags' => ['auth']],
        'Proxy-Features' => [],
        'Proxy-Instruction' => [],
        'Public' => [],
        'Public-Key-Pins' => ['tags' => ['deprecated', 'obsolete']],
        'Public-Key-Pins-Report-Only' => ['tags' => ['deprecated', 'obsolete']],

        'Range' => ['request' => true],
        'Referer' => ['request' => true],
        'Referrer-Policy' => ['response' => true, 'tags' => ['security'],
            'directives'=>[
                "no-referrer",
                "no-referrer-when-downgrade",
                "origin",
                "origin-when-cross-origin",
                "same-origin",
                "strict-origin",
                "strict-origin-when-cross-origin",
                "unsafe-url",
            ],
        ],
        'Refresh' => ['response' => true],
        'Report-To' => ['response' => true, 'tags' => ['deprecated', 'non-standard']],
        'Reporting-Endpoints' => ['response' => true, 'tags' => ['cors']],
        'Repr-Digest' => ['request' => true, 'response' => true, 'tags' => ['experimental']],
        'Retry-After' => ['response' => true],
        'RTT' => ['request' => true, 'tags' => ['experimental']],

        'Safe' => [],
        'Save-Data' => ['request' => true, 'tags' => ['experimental']],
        'Sec-Browsing-Topics' => ['request' => true, 'tags' => ['experimental', 'non-standard']],
        'Sec-CH-Prefers-Color-Scheme' => ['request' => true, 'tags' => ['experimental']],
        'Sec-CH-Prefers-Reduced-Motion' => ['request' => true, 'tags' => ['experimental']],
        'Sec-CH-Prefers-Reduced-Transparency' => ['request' => true, 'tags' => ['experimental']],
        'Sec-CH-UA' => ['request' => true, 'tags' => ['experimental']],
        'Sec-CH-UA-Arch' => ['request' => true, 'tags' => ['experimental']],
        'Sec-CH-UA-Bitness' => ['request' => true, 'tags' => ['experimental']],
        'Sec-CH-UA-Form-Factors' => ['request' => true, 'tags' => ['experimental']],
        'Sec-CH-UA-Full-Version' => ['request' => true, 'tags' => ['deprecated']],
        'Sec-CH-UA-Full-Version-List' => ['request' => true, 'tags' => ['experimental']],
        'Sec-CH-UA-Mobile' => ['request' => true, 'tags' => ['experimental']],
        'Sec-CH-UA-Model' => ['request' => true, 'tags' => ['experimental']],
        'Sec-CH-UA-Platform' => ['request' => true, 'tags' => ['experimental']],
        'Sec-CH-UA-Platform-Version' => ['request' => true, 'tags' => ['experimental']],
        'Sec-CH-UA-WoW64' => ['request' => true, 'tags' => ['experimental']],
        'Sec-Fetch-Dest' => ['request' => true, 'fetch-meta' => true, ],
        'Sec-Fetch-Mode' => ['request' => true, 'fetch-meta' => true, ],
        'Sec-Fetch-Site' => ['request' => true, 'fetch-meta' => true, ],
        'Sec-Fetch-Storage-Access' => ['request' => true, 'fetch-meta' => true, 'tags' => ['experimental']],
        'Sec-Fetch-User' => ['request' => true, 'fetch-meta' => true, ],
        'Sec-GPC' => ['request' => true, 'fetch-meta' => true, 'tags' => ['experimental']],
        'Sec-Purpose' => ['request' => true, 'fetch-meta' => true, ],
        'Sec-Speculation-Tags' => ['request' => true, 'tags' => ['experimental']],
        'Sec-WebSocket-Accept' => ['response' => true, ],
        'Sec-WebSocket-Extensions' => ['request' => true, 'response' => true, ],
        'Sec-WebSocket-Key' => ['request' => true],
        'Sec-W  ebSocket-Protocol' => ['request' => true, 'response' => true, ],
        'Sec-WebSocket-Version' => ['request' => true, 'response' => true, ],
        'Security-Scheme' => [],
        'Server' => ['response' => true, 'unwantedregex' => '[0-9]*\.[0-9\.]*'],
        'Server-Timing' => ['response' => true],
        'Service-Worker' => ['request' => true],
        'Service-Worker-Allowed' => ['response' => true],
        'Service-Worker-Navigation-Preload' => ['request' => true],
        'Set-Cookie' => ['response' => true],
        'Set-Login' => ['response' => true, ],
        'SetProfile' => [],
        'SoapAction' => [],
        'SourceMap'  => ['response' => true],
        'Speculation-Rules' => ['response' => true, 'tags' => ['experimental']],
        'Status' => ['response' => true, 'tags' => ['non-standard']],
        'Status-URI' => [],
        'Strict-Transport-Security' => ['response' => true, 'tags' => ['security'],
            'directives'=>[
                'max-age=<expire-time>',
                'includeSubDomains',
                'preload',
            ],
        ],
        'Supports-Loading-Mode' => ['response' => true, 'tags' => ['experimental']],
        'Surrogate-Capability' => [],
        'Surrogate-Control' => [],

        'TCN' => [],
        'TE' => ['request' => true, 
            'directives'=>[
                'compress',
                'deflate',
                'gzip',
                'trailers',
                'q',
            ],
        ],
        'Timeout' => [],
        'Timing-Allow-Origin' => ['response' => true, 'tags' => ['cors']],
        'Tk' => ['response' => true, 'tags' => ['deprecated', 'non-standard']],
        'Trailer' => ['request' => true, 'response' => true],
        'Transfer-Encoding' => ['request' => true, 'response' => true],

        'Upgrade' => ['request' => true, 'response' => true],
        'Upgrade-Insecure-Requests' => ['request' => true],
        'URI' => [],
        'Use-As-Dictionary' => ['response' => true, 'tags' => ['experimental']],
        'User-Agent' => ['request' => true],

        'Variant-Vary' => [],
        'Vary' => ['response' => true],
        'Via' => ['request' => true,  'response' => true],
        'Viewport-Width' => ['request' => true, 'tags' => ['deprecated', 'non-standard']],

        'Want-Digest' => ['response' => true],
        'Want-Content-Digest' => ['request'=>true, 'response' => true, 'tags' => ['experimental']],
        'Want-Repr-Digest' => ['request'=>true, 'response' => true, 'tags' => ['experimental']],
        'Warning' => ['request' => true, 'response' => true, 'tags' => ['deprecated']],
        'Width' => ['request' => true, 'tags' => ['deprecated', 'non-standard']],
        'WWW-Authenticate' => ['response' => true, 'tags' => ['auth']],

        'X-AspNet-Version' => ['response' => true, 'tags'=>['non-standard', 'unwanted']],
        'X-AspNetMvc-Version' => ['response' => true, 'tags'=>['non-standard', 'unwanted']],
        'X-Content-Duration' => ['response' => true, 'tags' => ['non-standard']],
        'X-Content-Security-Policy' => ['response' => true, 'tags' => ['non-standard']],
        'X-Content-Type-Options' => ['response' => true, 'tags' => ['security']],
        'X-Correlation-ID' => ['response' => true, 'tags' => ['non-standard']],
        'X-DNS-Prefetch-Control' => ['response' => true, 'tags' => ['non-standard']],
        'X-Forwarded-For' => ['request' => true, 'tags' => ['security-risk']],
        'X-Forwarded-Host' => ['request' => true,],
        'X-Forwarded-Proto' => ['request' => true,],
        'X-Frame-Options' => ['response' => true, 'tags' => ['deprecated', 'security'], 'badvalueregex' => 'ALLOW-FROM'],
        'X-Permitted-Cross-Domain-Policies' => ['response' => true, 'tags' => ['security']],
        'X-Pingback' => ['response' => true, 'tags' => ['non-standard']], // http://www.hixie.ch/specs/pingback/pingback#TOC2.1
        'X-Powered-By' => ['response' => true, 'tags' => ['non-standard', 'unwanted'], 'unwantedregex' => '[0-9]*\.[0-9\.]*'],
        'X-Request-ID' => ['response' => true, 'tags' => ['non-standard']],
        'X-Robots-Tag' => ['response' => true],
        'X-XSS-Protection' => ['response' => true, 'tags' => ['deprecated', 'non-standard']],
        'X-UA-Compatible' => ['response' => true, 'tags' => ['non-standard']],
        'X-WebKit-CSP' => ['response' => true, 'tags' => ['non-standard']],
    ],
];  