<?php
// ---------------------------------------------------------------------------
//
// Http header definitions
// This file read by httpheader.class.php
//
// ---------------------------------------------------------------------------
return [
        // en: https://en.wikipedia.org/wiki/List_of_HTTP_header_fields
        // de: https://de.wikipedia.org/wiki/Liste_der_HTTP-Headerfelder
        // ... plus https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
        'http' => array(
            '_status' => [],
            'Accept' => ['client'=>true],
            'Accept-Additions' => array(),
            'Accept-CH' => array('client'=>true),
            'Accept-Charset' => array('client'=>true),
            'Accept-CH-Lifetime' => array('client'=>true),
            'Accept-Encoding' => array('client'=>true),
            'Accept-Features' => array(),
            'Accept-Language' => array('client'=>true),
            'Accept-Patch' => array('response'=>true),
            'Accept-Ranges' => array('response'=>true),
            'Access-Control-Allow-Credentials' => array('response'=>true),
            'Access-Control-Allow-Headers' => array('response'=>true),
            'Access-Control-Allow-Methods' => array('response'=>true),
            'Access-Control-Allow-Origin' => array('response'=>true),
            'Access-Control-Expose-Headers' => array('response'=>true),
            'Access-Control-Max-Age' => array('response'=>true),
            'Access-Control-Request-Headers' => array(),
            'Access-Control-Request-Method' => array(),
            'Age' => array('tags' => array('cache')),
            'A-IM' => array(),
            'Allow' => array(),
            'Alternates' => array(),
            'Alt-Svc' => array(),
            'Authentication-Info' => array(),
            'Authorization' => array(),
            'Cache-Control' => array('tags' => array('cache')),
            'C-Ext' => array(),
            'Clear-Site-Data' => array(),
            'C-Man' => array(),
            'Connection' => array('response'=>true),
            'Content-Base' => array(),
            'Content-Disposition' => array('response'=>true),
            'Content-Encoding' => array('response'=>true, 'tags' => array('compression')),
            'Content-ID' => array(),
            'Content-Language' => array('response'=>true),
            'Content-Length' => array('response'=>true),
            'Content-Location' => array('response'=>true),
            'Content-MD5' => array(),
            'Content-Range' => array('response'=>true),
            'Content-Script-Type' => array(),
            'Content-Security-Policy' => array(),
            'Content-Security-Policy-Report-Only' => array(),
            'Content-Style-Type' => array(),
            'Content-Type' => array(),
            'Content-Version' => array(),
            'Cookie' => array(),
            'Cookie2' => array('obsolete'=>true),
            'C-Opt' => array(),
            'C-PEP-Info' => array(),
            'Cross-Origin-Resource-Policy' => array(),
            'Date' => array(),
            'DAV' => array(),
            'Default-Style' => array(),
            'Delta-Base' => array(),
            'Depth' => array(),
            'Derived-From' => array(),
            'Destination' => array(),
            'Device-Memory' => array(),
            'Differential-ID' => array(),
            'Digest' => array('response'=>true),
            'DNT' => array(),
            'DPR' => array(),
            'Early-Data' => array(),
            'ETag' => array('response'=>true, 'tags' => array('cache')),
            'Expect' => array('response'=>true),
            'Expect-CT' => array(),
            'Expires' => array('response'=>true, 'tags' => array('cache')),
            'Ext' => array(),
            'Feature-Policy' => array('response'=>true, 'tags' => array('feature', 'security'), "directives"=>array(
                "accelerometer",
                "ambient-light-sensor",
                "autoplay",
                "battery",
                "camera",
                "display-capture",
                "document-domain",
                "encrypted-media",
                "fullscreen",
                "geolocation",
                "gyroscope",
                "layout-animations",
                "legacy-image-formats",
                "magnetometer",
                "microphone",
                "midi",
                "oversized-images",
                "payment",
                "picture-in-picture",
                "publickey-credentials-get",
                "sync-xhr",
                "unoptimized-images",
                "unsized-media",
                "usb",
                "vibrate",
                "vr",
                "wake-lock",
                "xr",
                "xr-spatial-tracking"                
            )),
            'Forwarded' => array(),
            'From' => array('response'=>true),
            'GetProfile' => array(),
            'Host' => array('response'=>true),
            'If' => array(),
            'If-Match' => array('response'=>true),
            'If-Modified-Since' => array('response'=>true),
            'If-None-Match' => array('response'=>true),
            'If-Range' => array('response'=>true),
            'If-Unmodified-Since' => array('response'=>true),
            'IM' => array(),
            'Index' => array(),
            'Keep-Alive' => array('response'=>true),
            'Label' => array(),
            'Large-Allocation' => array(),
            'Last-Modified' => array('response'=>true),
            'Link' => array('response'=>true),
            'Location' => array('response'=>true),
            'Lock-Token' => array(),
            'Man' => array(),
            'Max-Forwards' => array(),
            'Meter' => array(),
            'MIME-Version' => array(),
            'Negotiate' => array(),
            'NEL' => array(),
            'Opt' => array(),
            'Ordering-Type' => array(),
            'Origin' => array(),
            'Overwrite' => array(),
            'P3P' => array(),
            'PEP' => array(),
            'Pep-Info' => array(),
            'PICS-Label' => array(),
            'Position' => array(),
            'Pragma' => array('response'=>true, 'tags' => array('cache', 'deprecated')),
            'ProfileObject' => array(),
            'Protocol' => array(),
            'Protocol-Info' => array(),
            'Protocol-Query' => array(),
            'Protocol-Request' => array(),
            'Proxy-Authenticate' => array('response'=>true),
            'Proxy-Authentication-Info' => array(),
            'Proxy-Authorization' => array('response'=>true),
            'Proxy-Features' => array(),
            'Proxy-Instruction' => array(),
            'Public' => array(),
            'Public-Key-Pins' => array('tags'=>array('deprecated', 'obsolete')),
            'Public-Key-Pins-Report-Only' => array('tags'=>array('deprecated', 'obsolete')),
            'Range' => array('response'=>true),
            'Referer' => array('response'=>true),
            'Referrer-Policy' => array(),
            'Retry-After' => array('response'=>true),
            'Safe' => array(),
            'Save-Data' => array(),
            'Sec-Fetch-Dest' => array(),
            'Sec-Fetch-Mode' => array(),
            'Sec-Fetch-Site' => array(),
            'Sec-Fetch-User' => array(),
            'Security-Scheme' => array(),
            'Sec-WebSocket-Accept' => array(),
            'Server' => array('response'=>true, 'unwantedregex' => '[0-9]*\.[0-9\.]*'),
            'Server-Timing' => array(),
            'Set-Cookie' => array('response'=>true),
            'Set-Cookie2' => array('obsolete'=>true, 'response'=>true),
            'SetProfile' => array(),
            'SoapAction' => array(),
            'SourceMap' => array(),
            'Status-URI' => array(),
            'Strict-Transport-Security' => array(),
            'Surrogate-Capability' => array(),
            'Surrogate-Control' => array(),
            'TCN' => array(),
            'TE' => array('response'=>true),
            'Timeout' => array(),
            'Timing-Allow-Origin' => array(),
            'Tk' => array(),
            'Trailer' => array('response'=>true),
            'Transfer-Encoding' => array('response'=>true),
            'Upgrade' => array(),
            'Upgrade-Insecure-Requests' => array(),
            'URI' => array(),
            'User-Agent' => array('response'=>true),
            'Variant-Vary' => array(),
            'Vary' => array('response'=>true),
            'Via' => array('response'=>true),
            'Want-Digest' => array('response'=>true),
            'Warning' => array('response'=>true),
            'WWW-Authenticate' => array('response'=>true),
            'X-Content-Type-Options' => array(),
            'X-DNS-Prefetch-Control' => array(),
            'X-Frame-Options' => array(),
            'X-XSS-Protection' => array(),
        // ),
        // see  https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_response_fields
        // 'non-standard' => array(
            'Refresh' => array('response'=>true, 'tags' => array('non-standard')),
            'Status' => array('response'=>true, 'tags' => array('non-standard')),
            'Timing-Allow-Origin' => array('response'=>true, 'tags' => array('non-standard')),
            'X-Content-Duration' => array('response'=>true, 'tags' => array('non-standard')),
            'X-Content-Security-Policy' => array('response'=>true, 'tags' => array('non-standard')),
            'X-Correlation-ID' => array('response'=>true, 'tags' => array('non-standard')),
            'X-Forwarded-For' => array('response'=>true, 'tags' => array('non-standard')),
            'X-Forwarded-Host' => array('response'=>true, 'tags' => array('non-standard')),
            'X-Forwarded-Proto' => array('response'=>true, 'tags' => array('non-standard')),
            'X-Pingback' => array('response'=>true, 'tags' => array('non-standard')), // http://www.hixie.ch/specs/pingback/pingback#TOC2.1
            'X-Powered-By' => array('response'=>true, 'tags' => array('non-standard', 'unwanted'), 'unwantedregex' => '[0-9]*\.[0-9\.]*'),
            'X-Request-ID' => array('response'=>true, 'tags' => array('non-standard')),
            'X-Robots-Tag' => array('response'=>true, 'tags' => array('non-standard')),
            'X-UA-Compatible' => array('response'=>true, 'tags' => array('non-standard')),
            'X-WebKit-CSP' => array('response'=>true, 'tags' => array('non-standard')),
        // ),
        // see https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#tab=Headers
        // 'security' => array(
            'Content-Security-Policy' =>           array('response'=>true, 'tags' => array('security'), 'badvalueregex' => 'unsafe\-'),
            'Expect-CT' =>                         array('response'=>true, 'tags' => array('security')),
            'Feature-Policy' =>                    array('response'=>true, 'tags' => array('feature', 'security')),
            'Public-Key-Pins' =>                   array('response'=>true, 'tags' => array('security', 'deprecated')),
            'Referrer-Policy' =>                   array('response'=>true, 'tags' => array('security')),
            'Strict-Transport-Security' =>         array('response'=>true, 'tags' => array('security')),
            'X-Content-Type-Options' =>            array('response'=>true, 'tags' => array('security')),
            'X-Frame-Options' =>                   array('response'=>true, 'tags' => array('security'), 'badvalueregex' => 'ALLOW-FROM'),
            'X-Permitted-Cross-Domain-Policies' => array('response'=>true, 'tags' => array('security')),
            'X-XSS-Protection' =>                  array('response'=>true, 'tags' => array('security')),
        ),
    ];